### ISSUE TITLE
Error when downloading all elements contained in a feature

### ISSUE THREAD

**Issue by DeniseGiub** [pypsa-meets-earth/earth-osm#14]
**Describe the bug**

Currently it is not possible to download everything contained inside a primary feature, without specifying the subfeatures.

**To Reproduce**

Steps to reproduce the described behavior:
1. Go to 'earth_osm/config.py'
2. Modify primary_feature_element this way:
primary_feature_element = {
    "feature": {
         True : "node",
    }
3. Run the workflow

**Expected behavior**
You will run into the following error:

Traceback (most recent call last):
  File "../bin/earth_osm", line 33, in <module>
    sys.exit(load_entry_point('earth-osm', 'console_scripts', 'earth_osm')())
  File "..earth-osm/earth_osm/args.py", line 119, in main
    f'Sub Features: {" - ".join(feature_list)}',
TypeError: sequence item 0: expected str instance, bool found

**Desktop**
 - OS: [Linux]

**Comment by davide-f** [comment]
@mnm-matin could you please add some comments on how you think it would be best handled this issue?
I think it would be interesting to have the guideline so that this issue could be addressed.
Many thanks :)

**Comment by mnm-matin** [comment]
I've been working on that commit for a while now, and have only picked it up again a few days ago. In particular the data pipeline needs to be modified so that it can handle: Node (Towers), Way (Lines and Cables), Area (Substations and Generators). There is some [detection](https://wiki.openstreetmap.org/wiki/Overpass_turbo/Polygon_Features) that needs to occur if something is a way or an area. [More info on ways from OSM](https://wiki.openstreetmap.org/wiki/Way). Ways are converted to LineStrings while Areas are converted to Polygons. Currently all Nodes are converted to Points which is wrong and would cause problems with buildings etc. [relevant code from osmnx here](https://github.com/gboeing/osmnx/blob/main/osmnx/geometries.py).

As a checklist:
- [ ] function way_or_area
- [ ] function way_to_linestring
- [ ] function area_to_polygon
- [ ] update the core data flow to use the new functions
- [ ] function polygon_to_point and add a --nodes-as-points flag to args
- [ ] update writing to csv
- [ ] update writing to gdf

**Comment by davide-f** [comment]
Mmm that sounds some work...
But do you think all of that is needed for buildings only?
The question here may not be download all "power", which indeed falls in all those troubles, but what about "buildings"?
What do you think is the procedure?
